### ISSUE TITLE
Minor updates to get project working locally for me

### ISSUE THREAD

**Issue by cxmiller21** [ArjanCodes/2022-dash#1]
Hi, thanks for creating this great project and series!!

When I started running the code I had to do two minor updates to get everything working locally on my Macbook m1 machine. I might have missed a prerequisite step(s) where you covered these in which case, my apologies for missing them.

In the "./environment/requirements.txt" file, I had to change `python-i18n` to `python-i18n[YAML]` to have the i18n translations recognize the yaml file values.
<img width="1508" alt="Screen Shot 2022-08-27 at 2 06 21 PM" src="https://user-images.githubusercontent.com/91931784/187044635-07a05af3-cf09-48c1-b446-5a4aa9a4c75d.png">

In the "./environment/README.md" file, I was using the pip install version and had to change `python -m pip install ./environment/requirements.txt` to `python -m pip install -r ./environment/requirements.txt`
<img width="763" alt="Screen Shot 2022-08-27 at 2 08 08 PM" src="https://user-images.githubusercontent.com/91931784/187044662-a7cfa76e-bae3-4b8a-a8e7-4b134aa9b87c.png">

**Comment by egges** [comment]
Thanks for noticing that - I've fixed it just now.
